/**
 * คิวรีอ่าน dbo.biopsy จาก MSSQL แบบแบ่งหน้า
 */
export const MSSQL_PROCEDURE_SELECT = `
SELECT
  CAST(CAST([Exam_ID] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS exam_id,
  CAST(CAST([BiopsyID] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS biopsy_id,
  CONVERT(VARCHAR(30), [Exam_date], 126) AS exam_date,
  CAST([PID] AS NVARCHAR(MAX)) AS pid,
  CAST([Radiologist] AS NVARCHAR(MAX)) AS radiologist,
  CAST([Clinical] AS NVARCHAR(MAX)) AS clinical,
  CAST([Finding] AS NVARCHAR(MAX)) AS finding,
  CAST([Location] AS NVARCHAR(MAX)) AS location,
  CAST(CAST([BiopsyProc] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS biopsy_proc,
  CAST([BiopsyProc_Des] AS NVARCHAR(MAX)) AS biopsy_proc_des,
  CAST([NeedleNo] AS NVARCHAR(MAX)) AS needle_no,
  CAST(CAST([Technique] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS technique,
  CAST([Technique_Des] AS NVARCHAR(MAX)) AS technique_des,
  CAST(CAST([PatientPos] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS patient_pos,
  CAST([PatientPos_Des] AS NVARCHAR(MAX)) AS patient_pos_des,
  CAST(CAST([BreastCompress] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS breast_compress,
  CAST([BreastCompress_Des] AS NVARCHAR(MAX)) AS breast_compress_des,
  CAST(CAST([Approach] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS approach,
  CAST([Approach_Des] AS NVARCHAR(MAX)) AS approach_des,
  CAST(CAST([SpontaneousDischarge] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS spontaneous_discharge,
  CAST([Result_Aspiration_CC] AS NVARCHAR(MAX)) AS result_aspiration_cc,
  CAST(CAST([Result_Aspiration_App] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS result_aspiration_app,
  CAST([Result_Aspiration_App_Des] AS NVARCHAR(MAX)) AS result_aspiration_app_des,
  CAST(CAST([Result_Aspiration_Cytology] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS result_aspiration_cytology,
  CAST(CAST([Result_Aspiration_Culture] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS result_aspiration_culture,
  CAST([Result_CoreBiopsy_Specimens] AS NVARCHAR(MAX)) AS result_corebiopsy_specimens,
  CAST([Result_CoreBiopsy_Microcal] AS NVARCHAR(MAX)) AS result_corebiopsy_microcal,
  CAST(CAST([Result_Needle_within_Lesion] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS result_needle_within_lesion,
  CAST([Result_Needle_mm_depth] AS NVARCHAR(MAX)) AS result_needle_mm_depth,
  CAST([Result_Needle_mm_near] AS NVARCHAR(MAX)) AS result_needle_mm_near,
  CAST([Result_Needle_Other] AS NVARCHAR(MAX)) AS result_needle_other,
  CAST(CAST([Result_Ductography] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS result_ductography,
  CAST([Result_Ductography_Des] AS NVARCHAR(MAX)) AS result_ductography_des,
  CAST([Result_Ductography_Other] AS NVARCHAR(MAX)) AS result_ductography_other,
  CAST([Result_Smear_Noofslide] AS NVARCHAR(MAX)) AS result_smear_noofslide,
  CAST([Result_Smear_App] AS NVARCHAR(MAX)) AS result_smear_app,
  CAST([Result_Smear_App_Des] AS NVARCHAR(MAX)) AS result_smear_app_des,
  CAST(CAST([Assessment_BIRADS] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS assessment_birads,
  CAST([Assessment_BIRADS_Des] AS NVARCHAR(MAX)) AS assessment_birads_des,
  CAST(CAST([Assessment_Others] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS assessment_others,
  CAST([Assessment_Others_Des] AS NVARCHAR(MAX)) AS assessment_others_des,
  CAST(CAST([Recommend] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS recommend,
  CAST([Recommend_Des] AS NVARCHAR(MAX)) AS recommend_des,
  CAST(CAST([Recommend_Benign] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS recommend_benign,
  CAST([Recommend_Benign_Des] AS NVARCHAR(MAX)) AS recommend_benign_des,
  CAST(CAST([Recommend_Highrisk] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS recommend_highrisk,
  CAST([Recommend_Highrisk_Des] AS NVARCHAR(MAX)) AS recommend_highrisk_des,
  CAST(CAST([Recommend_Malignant] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS recommend_malignant,
  CAST([Recommend_Malignant_Des] AS NVARCHAR(MAX)) AS recommend_malignant_des,
  CAST([Summary_Doctor] AS NVARCHAR(MAX)) AS summary_doctor,
  CAST([Summary_Doctor_Name] AS NVARCHAR(MAX)) AS summary_doctor_name,
  CAST([SpecialCase] AS NVARCHAR(MAX)) AS special_case,
  CAST([SpecialCase_Point_Des] AS NVARCHAR(MAX)) AS special_case_point_des,
  CAST([SpecialCase_Point] AS NVARCHAR(MAX)) AS special_case_point,
  CAST([SpecialCase_Detail] AS NVARCHAR(MAX)) AS special_case_detail,
  CAST([PathoCode] AS NVARCHAR(MAX)) AS patho_code,
  CAST([PathoCode_FullDes] AS NVARCHAR(MAX)) AS patho_code_full_des,
  CAST([PathoCode_FillBy] AS NVARCHAR(MAX)) AS patho_code_fill_by,
  CONVERT(VARCHAR(30), [PathoCode_ResultDate], 126) AS patho_code_result_date,
  CAST(CAST([IsFinal] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS is_final,
  CAST(CAST([PatientType] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS patient_type,
  CAST([PatientType_Des] AS NVARCHAR(MAX)) AS patient_type_des,
  CAST(CAST([Remark] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS remark,
  CAST([Remark_Other] AS NVARCHAR(MAX)) AS remark_other,
  CAST([Remark_Text] AS NVARCHAR(MAX)) AS remark_text,
  CAST([Width] AS NVARCHAR(MAX)) AS width,
  CAST([Depth] AS NVARCHAR(MAX)) AS depth,
  CAST([Corrected] AS NVARCHAR(MAX)) AS corrected,
  CONVERT(VARCHAR(30), [CorrectedDate], 126) AS corrected_date,
  CAST([Location_Left_Other] AS NVARCHAR(MAX)) AS location_left_other,
  CAST([Location_Right_Other] AS NVARCHAR(MAX)) AS location_right_other,
  CAST(CAST([last_exam_id] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS last_exam_id
FROM {{sourceObject}}
ORDER BY {{orderBy}}
OFFSET @offset ROWS FETCH NEXT @page ROWS ONLY;
`.trim();
