/**
 * คิวรีอ่าน dbo.examination จาก MSSQL แบบแบ่งหน้า
 */
export const MSSQL_EXAMINATION_SELECT = `
SELECT
  CAST(CAST([Exam_ID] AS BIGINT) AS NVARCHAR(MAX)) AS exam_id,
  CONVERT(VARCHAR(30), [Exam_date], 126) AS exam_date,
  CAST([PID] AS NVARCHAR(MAX)) AS pid,
  CAST([Tech_LoginName] AS NVARCHAR(MAX)) AS tech_login_name,
  CAST([mobile] AS NVARCHAR(MAX)) AS mobile,
  CAST([mobile_update] AS NVARCHAR(MAX)) AS mobile_update,
  CAST(CAST([menstruation_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS menstruation_age,
  CAST(CAST([menopause_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS menopause_age,
  CAST(CAST([first_pregnancy_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS first_pregnancy_age,
  CAST(CAST([num_pregnancy] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_pregnancy,
  CAST([cont_use] AS NVARCHAR(MAX)) AS cont_use,
  CAST(CAST([cont_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS cont_yrs,
  CAST([hormone_use] AS NVARCHAR(MAX)) AS hormone_use,
  CAST(CAST([hormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS hormone_yrs,
  CAST([hysterectomy] AS NVARCHAR(MAX)) AS hysterectomy,
  CAST([ovaries_removed] AS NVARCHAR(MAX)) AS ovaries_removed,
  CAST([Pragnant] AS NVARCHAR(MAX)) AS pragnant,
  CAST([Referring_MD] AS NVARCHAR(MAX)) AS referring_md,
  CAST([Referring_Hospital] AS NVARCHAR(MAX)) AS referring_hospital,
  CONVERT(VARCHAR(30), [prev_mammo_date], 126) AS prev_mammo_date,
  CAST([prev_mammo_loc] AS NVARCHAR(MAX)) AS prev_mammo_loc,
  CAST(CAST([sister_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS sister_cancer_age,
  CAST(CAST([mother_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS mother_cancer_age,
  CAST(CAST([grandmother_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS grandmother_cancer_age,
  CAST(CAST([other_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS other_cancer_age,
  CONVERT(VARCHAR(30), [biopsy_l_date], 126) AS biopsy_l_date,
  CONVERT(VARCHAR(30), [biopsy_r_date], 126) AS biopsy_r_date,
  CONVERT(VARCHAR(30), [chemo_l_date], 126) AS chemo_l_date,
  CONVERT(VARCHAR(30), [chemo_r_date], 126) AS chemo_r_date,
  CONVERT(VARCHAR(30), [cyst_l_date], 126) AS cyst_l_date,
  CONVERT(VARCHAR(30), [cyst_r_date], 126) AS cyst_r_date,
  CONVERT(VARCHAR(30), [irr_l_date], 126) AS irr_l_date,
  CONVERT(VARCHAR(30), [irr_r_date], 126) AS irr_r_date,
  CONVERT(VARCHAR(30), [lump_l_date], 126) AS lump_l_date,
  CONVERT(VARCHAR(30), [lump_r_date], 126) AS lump_r_date,
  CONVERT(VARCHAR(30), [mast_l_date], 126) AS mast_l_date,
  CONVERT(VARCHAR(30), [mast_r_date], 126) AS mast_r_date,
  CONVERT(VARCHAR(30), [rad_l_date], 126) AS rad_l_date,
  CONVERT(VARCHAR(30), [rad_r_date], 126) AS rad_r_date,
  CAST(CAST([num_left_mass] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_left_mass,
  CAST(CAST([num_right_mass] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_right_mass,
  CAST([lnwn] AS NVARCHAR(MAX)) AS lnwn,
  CAST([lnww] AS NVARCHAR(MAX)) AS lnww,
  CAST([ln] AS NVARCHAR(MAX)) AS ln,
  CAST([lnen] AS NVARCHAR(MAX)) AS lnen,
  CAST([lnee] AS NVARCHAR(MAX)) AS lnee,
  CAST([le] AS NVARCHAR(MAX)) AS le,
  CAST([lm] AS NVARCHAR(MAX)) AS lm,
  CAST([lw] AS NVARCHAR(MAX)) AS lw,
  CAST([lsws] AS NVARCHAR(MAX)) AS lsws,
  CAST([lsww] AS NVARCHAR(MAX)) AS lsww,
  CAST([ls] AS NVARCHAR(MAX)) AS ls,
  CAST([lses] AS NVARCHAR(MAX)) AS lses,
  CAST([lsee] AS NVARCHAR(MAX)) AS lsee,
  CAST([rnwn] AS NVARCHAR(MAX)) AS rnwn,
  CAST([rnww] AS NVARCHAR(MAX)) AS rnww,
  CAST([rn] AS NVARCHAR(MAX)) AS rn,
  CAST([rnen] AS NVARCHAR(MAX)) AS rnen,
  CAST([rnee] AS NVARCHAR(MAX)) AS rnee,
  CAST([re] AS NVARCHAR(MAX)) AS re,
  CAST([rm] AS NVARCHAR(MAX)) AS rm,
  CAST([rw] AS NVARCHAR(MAX)) AS rw,
  CAST([rsws] AS NVARCHAR(MAX)) AS rsws,
  CAST([rsww] AS NVARCHAR(MAX)) AS rsww,
  CAST([rs] AS NVARCHAR(MAX)) AS rs,
  CAST([rses] AS NVARCHAR(MAX)) AS rses,
  CAST([rsee] AS NVARCHAR(MAX)) AS rsee,
  CAST([lother] AS NVARCHAR(MAX)) AS lother,
  CAST([rother] AS NVARCHAR(MAX)) AS rother,
  CAST([lAxillar] AS NVARCHAR(MAX)) AS l_axillar,
  CAST([rAxillar] AS NVARCHAR(MAX)) AS r_axillar,
  CAST([Exam_Reason] AS NVARCHAR(MAX)) AS exam_reason,
  CAST([Exam_Reason_text] AS NVARCHAR(MAX)) AS exam_reason_text,
  CAST([Exam_Reason_Memotext] AS NVARCHAR(MAX)) AS exam_reason_memotext,
  CAST(CAST([Pain_l_duration] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS pain_l_duration,
  CAST(CAST([Pain_r_duration] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS pain_r_duration,
  CONVERT(VARCHAR(30), [MobileUpdated], 126) AS mobile_updated,
  CAST([Mobile_Loc] AS NVARCHAR(MAX)) AS mobile_loc,
  CONVERT(VARCHAR(30), [bct_r_date], 126) AS bct_r_date,
  CONVERT(VARCHAR(30), [bct_l_date], 126) AS bct_l_date,
  CAST(CAST([patient_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS patient_cancer_age,
  CAST(CAST([daughter_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS daughter_cancer_age,
  CAST([daughter_cancer_age_more] AS NVARCHAR(MAX)) AS daughter_cancer_age_more,
  CAST([sister_cancer_age_more] AS NVARCHAR(MAX)) AS sister_cancer_age_more,
  CAST([other_cancer_age_more] AS NVARCHAR(MAX)) AS other_cancer_age_more,
  CAST(CAST([stophormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stophormone_yrs,
  CAST([CAhormone_use] AS NVARCHAR(MAX)) AS ca_hormone_use,
  CAST(CAST([CAhormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS ca_hormone_yrs,
  CAST(CAST([stopCAhormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stop_ca_hormone_yrs,
  CAST(CAST([stopContr_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stop_contr_yrs,
  CONVERT(VARCHAR(30), [rm_l_date], 126) AS rm_l_date,
  CONVERT(VARCHAR(30), [rm_r_date], 126) AS rm_r_date,
  CONVERT(VARCHAR(30), [ri_l_date], 126) AS ri_l_date,
  CONVERT(VARCHAR(30), [ri_r_date], 126) AS ri_r_date,
  CONVERT(VARCHAR(30), [fna_l_date], 126) AS fna_l_date,
  CONVERT(VARCHAR(30), [fna_r_date], 126) AS fna_r_date,
  CONVERT(VARCHAR(30), [fnx_l_date], 126) AS fnx_l_date,
  CONVERT(VARCHAR(30), [fnx_r_date], 126) AS fnx_r_date,
  CAST([sendExam_LoginName] AS NVARCHAR(MAX)) AS send_exam_login_name,
  CAST(CAST([Schedule_ID] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS schedule_id
FROM {{sourceObject}}
WHERE ({{examNumericKeyRange}})
ORDER BY {{orderBy}}
OFFSET @offset ROWS FETCH NEXT @page ROWS ONLY;
`.trim();

const EXAMINATION_SELECT_COLUMNS = `
  CAST(CAST([Exam_ID] AS BIGINT) AS NVARCHAR(MAX)) AS exam_id,
  CONVERT(VARCHAR(30), [Exam_date], 126) AS exam_date,
  CAST([PID] AS NVARCHAR(MAX)) AS pid,
  CAST([Tech_LoginName] AS NVARCHAR(MAX)) AS tech_login_name,
  CAST([mobile] AS NVARCHAR(MAX)) AS mobile,
  CAST([mobile_update] AS NVARCHAR(MAX)) AS mobile_update,
  CAST(CAST([menstruation_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS menstruation_age,
  CAST(CAST([menopause_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS menopause_age,
  CAST(CAST([first_pregnancy_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS first_pregnancy_age,
  CAST(CAST([num_pregnancy] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_pregnancy,
  CAST([cont_use] AS NVARCHAR(MAX)) AS cont_use,
  CAST(CAST([cont_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS cont_yrs,
  CAST([hormone_use] AS NVARCHAR(MAX)) AS hormone_use,
  CAST(CAST([hormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS hormone_yrs,
  CAST([hysterectomy] AS NVARCHAR(MAX)) AS hysterectomy,
  CAST([ovaries_removed] AS NVARCHAR(MAX)) AS ovaries_removed,
  CAST([Pragnant] AS NVARCHAR(MAX)) AS pragnant,
  CAST([Referring_MD] AS NVARCHAR(MAX)) AS referring_md,
  CAST([Referring_Hospital] AS NVARCHAR(MAX)) AS referring_hospital,
  CONVERT(VARCHAR(30), [prev_mammo_date], 126) AS prev_mammo_date,
  CAST([prev_mammo_loc] AS NVARCHAR(MAX)) AS prev_mammo_loc,
  CAST(CAST([sister_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS sister_cancer_age,
  CAST(CAST([mother_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS mother_cancer_age,
  CAST(CAST([grandmother_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS grandmother_cancer_age,
  CAST(CAST([other_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS other_cancer_age,
  CONVERT(VARCHAR(30), [biopsy_l_date], 126) AS biopsy_l_date,
  CONVERT(VARCHAR(30), [biopsy_r_date], 126) AS biopsy_r_date,
  CONVERT(VARCHAR(30), [chemo_l_date], 126) AS chemo_l_date,
  CONVERT(VARCHAR(30), [chemo_r_date], 126) AS chemo_r_date,
  CONVERT(VARCHAR(30), [cyst_l_date], 126) AS cyst_l_date,
  CONVERT(VARCHAR(30), [cyst_r_date], 126) AS cyst_r_date,
  CONVERT(VARCHAR(30), [irr_l_date], 126) AS irr_l_date,
  CONVERT(VARCHAR(30), [irr_r_date], 126) AS irr_r_date,
  CONVERT(VARCHAR(30), [lump_l_date], 126) AS lump_l_date,
  CONVERT(VARCHAR(30), [lump_r_date], 126) AS lump_r_date,
  CONVERT(VARCHAR(30), [mast_l_date], 126) AS mast_l_date,
  CONVERT(VARCHAR(30), [mast_r_date], 126) AS mast_r_date,
  CONVERT(VARCHAR(30), [rad_l_date], 126) AS rad_l_date,
  CONVERT(VARCHAR(30), [rad_r_date], 126) AS rad_r_date,
  CAST(CAST([num_left_mass] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_left_mass,
  CAST(CAST([num_right_mass] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS num_right_mass,
  CAST([lnwn] AS NVARCHAR(MAX)) AS lnwn,
  CAST([lnww] AS NVARCHAR(MAX)) AS lnww,
  CAST([ln] AS NVARCHAR(MAX)) AS ln,
  CAST([lnen] AS NVARCHAR(MAX)) AS lnen,
  CAST([lnee] AS NVARCHAR(MAX)) AS lnee,
  CAST([le] AS NVARCHAR(MAX)) AS le,
  CAST([lm] AS NVARCHAR(MAX)) AS lm,
  CAST([lw] AS NVARCHAR(MAX)) AS lw,
  CAST([lsws] AS NVARCHAR(MAX)) AS lsws,
  CAST([lsww] AS NVARCHAR(MAX)) AS lsww,
  CAST([ls] AS NVARCHAR(MAX)) AS ls,
  CAST([lses] AS NVARCHAR(MAX)) AS lses,
  CAST([lsee] AS NVARCHAR(MAX)) AS lsee,
  CAST([rnwn] AS NVARCHAR(MAX)) AS rnwn,
  CAST([rnww] AS NVARCHAR(MAX)) AS rnww,
  CAST([rn] AS NVARCHAR(MAX)) AS rn,
  CAST([rnen] AS NVARCHAR(MAX)) AS rnen,
  CAST([rnee] AS NVARCHAR(MAX)) AS rnee,
  CAST([re] AS NVARCHAR(MAX)) AS re,
  CAST([rm] AS NVARCHAR(MAX)) AS rm,
  CAST([rw] AS NVARCHAR(MAX)) AS rw,
  CAST([rsws] AS NVARCHAR(MAX)) AS rsws,
  CAST([rsww] AS NVARCHAR(MAX)) AS rsww,
  CAST([rs] AS NVARCHAR(MAX)) AS rs,
  CAST([rses] AS NVARCHAR(MAX)) AS rses,
  CAST([rsee] AS NVARCHAR(MAX)) AS rsee,
  CAST([lother] AS NVARCHAR(MAX)) AS lother,
  CAST([rother] AS NVARCHAR(MAX)) AS rother,
  CAST([lAxillar] AS NVARCHAR(MAX)) AS l_axillar,
  CAST([rAxillar] AS NVARCHAR(MAX)) AS r_axillar,
  CAST([Exam_Reason] AS NVARCHAR(MAX)) AS exam_reason,
  CAST([Exam_Reason_text] AS NVARCHAR(MAX)) AS exam_reason_text,
  CAST([Exam_Reason_Memotext] AS NVARCHAR(MAX)) AS exam_reason_memotext,
  CAST(CAST([Pain_l_duration] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS pain_l_duration,
  CAST(CAST([Pain_r_duration] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS pain_r_duration,
  CONVERT(VARCHAR(30), [MobileUpdated], 126) AS mobile_updated,
  CAST([Mobile_Loc] AS NVARCHAR(MAX)) AS mobile_loc,
  CONVERT(VARCHAR(30), [bct_r_date], 126) AS bct_r_date,
  CONVERT(VARCHAR(30), [bct_l_date], 126) AS bct_l_date,
  CAST(CAST([patient_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS patient_cancer_age,
  CAST(CAST([daughter_cancer_age] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS daughter_cancer_age,
  CAST([daughter_cancer_age_more] AS NVARCHAR(MAX)) AS daughter_cancer_age_more,
  CAST([sister_cancer_age_more] AS NVARCHAR(MAX)) AS sister_cancer_age_more,
  CAST([other_cancer_age_more] AS NVARCHAR(MAX)) AS other_cancer_age_more,
  CAST(CAST([stophormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stophormone_yrs,
  CAST([CAhormone_use] AS NVARCHAR(MAX)) AS ca_hormone_use,
  CAST(CAST([CAhormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS ca_hormone_yrs,
  CAST(CAST([stopCAhormone_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stop_ca_hormone_yrs,
  CAST(CAST([stopContr_yrs] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS stop_contr_yrs,
  CONVERT(VARCHAR(30), [rm_l_date], 126) AS rm_l_date,
  CONVERT(VARCHAR(30), [rm_r_date], 126) AS rm_r_date,
  CONVERT(VARCHAR(30), [ri_l_date], 126) AS ri_l_date,
  CONVERT(VARCHAR(30), [ri_r_date], 126) AS ri_r_date,
  CONVERT(VARCHAR(30), [fna_l_date], 126) AS fna_l_date,
  CONVERT(VARCHAR(30), [fna_r_date], 126) AS fna_r_date,
  CONVERT(VARCHAR(30), [fnx_l_date], 126) AS fnx_l_date,
  CONVERT(VARCHAR(30), [fnx_r_date], 126) AS fnx_r_date,
  CAST([sendExam_LoginName] AS NVARCHAR(MAX)) AS send_exam_login_name,
  CAST(CAST([Schedule_ID] AS NVARCHAR(50)) AS NVARCHAR(MAX)) AS schedule_id
`.trim();

export const MSSQL_EXAMINATION_ID_SELECT = `
SELECT TOP (@page)
  CAST([Exam_ID] AS BIGINT) AS exam_id
FROM {{sourceObject}}
WHERE [Exam_ID] > @afterExamId AND ({{examNumericKeyRange}})
ORDER BY [Exam_ID] ASC
`.trim();

export const MSSQL_EXAMINATION_DETAIL_BY_IDS_SELECT = `
SELECT
  ${EXAMINATION_SELECT_COLUMNS}
FROM {{sourceObject}}
WHERE [Exam_ID] IN ({{idPlaceholders}})
ORDER BY [Exam_ID] ASC
`.trim();
